backend = "glx";
vsync = true;

corner-radius = 10;
shadow = false;
fading = true;

fade-in-step = 0.02; 
fade-out-step = 0.02; 
fade-delta = 5;

rounded-corners-exclude = [ "class_g = 'dwm'", "class_g = 'dmenu'" ]
